// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGrQC1_HQMnn9dUNLVq48J_Dl5guM0Dpw',
    appId: '1:808078395076:web:70c4ea7f033de265d52b91',
    messagingSenderId: '808078395076',
    projectId: 'flutter-chat-app-9a9e3',
    authDomain: 'flutter-chat-app-9a9e3.firebaseapp.com',
    storageBucket: 'flutter-chat-app-9a9e3.appspot.com',
    measurementId: 'G-SCN4G5XZVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtKDd6l-1R3XTZ8t-njNy6rEN2Za5G-as',
    appId: '1:808078395076:android:3e6e4ef9b5c6b111d52b91',
    messagingSenderId: '808078395076',
    projectId: 'flutter-chat-app-9a9e3',
    storageBucket: 'flutter-chat-app-9a9e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDA252zqre-yPhFgPG_ARIjZet7Hv2dsI',
    appId: '1:808078395076:ios:041ae10df90c75cbd52b91',
    messagingSenderId: '808078395076',
    projectId: 'flutter-chat-app-9a9e3',
    storageBucket: 'flutter-chat-app-9a9e3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDA252zqre-yPhFgPG_ARIjZet7Hv2dsI',
    appId: '1:808078395076:ios:66dfcf4323b133e5d52b91',
    messagingSenderId: '808078395076',
    projectId: 'flutter-chat-app-9a9e3',
    storageBucket: 'flutter-chat-app-9a9e3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
